# Project-wide Gradle settings.
# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE are overridden by the Gradle
# properties specified in this file. For more details on how to customize your build
# environment using the gradle.properties file, see the Gradle documentation at
# https://docs.gradle.org/current/userguide/build_environment.html
#
# The settings specified in this file apply to all builds, regardless of whether they
# are run from the command line or the IDE.
#
# 1. If you want to disable the daemon, use org.gradle.daemon=false
# 2. When converted to a reduced character set encoding, the new Gradle daemon won't
# connect to the old GRADLE daemon. The solution is to rm ~/.gradle or run
# ./gradlew --stop
#
# For more on this and other options, visit https://docs.gradle.org/current/userguide/build_environment.html

# Enables nanoPb to use the lite runtime.
android.useAndroidX=true
android.enableJetifier=true
